Repository AY2425S2-CS2103T-T10-3/tp, pull requests merged in 2025-03, with the labels that each got.

#9 Add Billy's Photo
  docs/images/billy026.png
Labels: type.Task, priority.Low

#7 Add Minh's photo
  .gitignore
  docs/images/minhkiwi14.png
Labels: type.Task, priority.Low

#18 Add Zayd's Details
  docs/AboutUs.md
  docs/team/zaydmahmud.md
Labels: type.Task, priority.Low

#21 Add vikram goyal info
  docs/AboutUs.md
  docs/team/vikramgoyal.md
Labels: type.Task, priority.Low

#12 Add Fai Yew's details in documentation
  docs/AboutUs.md
  docs/team/kwanfaiyew.md
Labels: priority.Low

#20 Update AboutUs
  docs/AboutUs.md
  docs/images/billy026.png
  docs/team/billyandina.md
Labels: type.Task, priority.Low

#17 Add Minh's details in Documentation
  docs/AboutUs.md
  docs/team/minh.md
Labels: type.Task, priority.Low

#26 Update build status badge
  README.md
Labels: type.Task, priority.Low

#27 Fix Fai Yew broken image
  docs/AboutUs.md
Labels: priority.Low

#30 Add new UI Mockup
  docs/images/Ui.png
Labels: type.Task, priority.Medium

#31 Update README.md and product name in index.md
  README.md
  docs/index.md
Labels: type.Task, priority.Medium

#47 Add a class to represent academic courses
  src/main/java/seedu/address/model/person/Course.java
Labels: type.Task, priority.High

#48 Update Person.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task, priority.High

#51 E refactor everything oh my
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Participation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Enhancement, priority.Medium, severity.High

#52 Update ArgumentTokenizer to handle '/option arg1' instead of 'option/…
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: type.Task, type.Bug, priority.High, severity.High

#54 Remove remark command
  docs/diagrams/add-remark/ParserClass.puml
  docs/diagrams/add-remark/RemarkClass.puml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#56 Storage Update
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Enhancement, priority.High

#57 Add functionality to 'find' to allow searching for substrings and ID
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.High

#58 Fix syntax errors
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, priority.High

#59 Fix ArgumentMultimap, ArgumentTokenizer to parse Add command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, priority.High, severity.High

#68 E modify with functions creating Person class with new properties
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Participation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/ParticipationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High, severity.Medium

#91 Update AddCommandParser and AddCommandParserTest
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, priority.High, severity.High

#92 Update EditCommandTest and EditCommandParserTest
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Enhancement, priority.High, severity.High

#93 Fix AddCommandParserTest
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Enhancement, type.Bug, severity.Medium

#95 Add functionality to search for Course names
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Medium

#96 Update GradeTest
  src/test/java/seedu/address/model/person/GradeTest.java
Labels: type.Enhancement, priority.High, priority.Medium, severity.Medium

#98 Update ArgumentTokenizerTest
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#97 Update the NameContainsKeywordsPredicateTest class
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.High, severity.High

#99 Update EditPersonDescriptorTest, UniquePersonListTest and JsonSerializableAddressBookTest
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High, severity.High

#100 Update PersonTest
  .gitignore
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High, severity.High

#101 Update delete command and tests
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#102 Update AddCommandIntegrationTest
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
Labels: type.Bug, priority.High, severity.Low

#103 Update JsonAdaptedPersonTest
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High, severity.High

#104 Update AddressBookTest
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task, priority.High, severity.High

#105 Fix Checkstyle errors
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Participation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task, priority.Medium, severity.VeryLow

#107 Fix AddressBookParserTest#parseCommand_add
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.High, severity.High

#106 Fix Checkstyle errors in test classes
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/ParticipationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium, severity.VeryLow

#109 Checkstyle throws an error for assertionThrow format
  config/checkstyle/suppressions.xml
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.Medium, severity.VeryLow

#108 Update LogicManagerTest
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task, priority.High, severity.High

#112 Fix format for delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task, priority.Low, severity.VeryLow

#113 Fix checkStyle for delete command
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: severity.VeryLow

#115 Fix bug in LogicManagerTest
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#116 Edit User Guide
  build.gradle
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#119 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#131 Update the validation regex and message constraint
  src/main/java/seedu/address/model/person/Course.java
Labels: type.Enhancement, priority.High, severity.High

#118 User guide update from vikram
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#137 Update ArchitectureSequenceDiagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: type.Task, priority.Medium, severity.VeryLow

#136 Add `file` command
  .vscode/settings.json
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FileCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FileCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/FileCommandTest.java
  src/test/java/seedu/address/logic/parser/FileCommandParserTest.java
Labels: type.Story, priority.Medium

#138 Add Sorting
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Enhancement, priority.Medium

#142 Add test classes for sort functionality and modify existing classes
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Task, priority.Medium

#139 Add Student Grades to Address Books
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium

#144 Merge conflicts
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story, priority.High, severity.High

#148 Update User Guide
  docs/UserGuide.md
  docs/images/person.png
Labels: type.Task, priority.Medium, severity.VeryLow

#147 Create Display command
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/Histogram.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/Histogram.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Story, priority.High, severity.High

#149 Update GUI
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium, severity.Medium

#150 Update dynamic display and axis labels of Histogram
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/Histogram.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/Histogram.fxml
Labels: type.Bug, priority.Medium, severity.High

#151 Add an assertion
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Task, priority.High, severity.Low

#152 Update test cases
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#153 Update file command and checkstyle
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FileCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/Histogram.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, severity.Low

#154 Update checkstyles
  README.md
  docs/UserGuide.md
  src/main/resources/view/Histogram.fxml
Labels: type.Bug, priority.High, severity.High

#155 Update DeleteSequenceDiagram
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.Medium, severity.VeryLow

#156 Add notes feature backend logic
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Story, priority.Medium, severity.Medium

#157 Add new tests for ParserUtil
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Task, priority.Medium, severity.VeryLow

#160 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: type.Task, priority.Medium, severity.VeryLow

#162 Add ResetRecordsCommand
  src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High, severity.High
