Repository AY2425S2-CS2103T-T10-3/tp, pull requests merged in 2025-04, with the labels that each got.

#179 Add reset records command test
  src/test/java/seedu/address/logic/commands/ResetRecordsCommandTest.java
Labels: type.Task, priority.Medium, severity.Low

#194 Modify the resetRecords method and the affected test
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/ResetRecordsCommandTest.java
Labels: type.Task, priority.High, severity.High

#196 Edit the Sort command to take in four different parameters (one at a
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/SortDescriptorTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#197 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/person.png
Labels: type.Task, priority.Medium, severity.VeryLow

#200 Fix bugs regarding Phone
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#199 Fix bugs regarding name
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High, severity.Medium

#203 Fix bugs related to Course
  src/main/java/seedu/address/model/person/Course.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.Medium, severity.Low

#198 Fix alpha bugs related to File command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FileCommand.java
  src/main/java/seedu/address/logic/parser/FileCommandParser.java
  src/test/java/seedu/address/logic/commands/FileCommandTest.java
  src/test/java/seedu/address/logic/parser/FileCommandParserTest.java
Labels: type.Bug, severity.Low, alpha-bug

#202 Update User Guide and README to contain the command ResetRecords
  README.md
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.High

#211 Fix bugs regarding Grade
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.High, severity.Medium

#218 Update the link to the User Guide in the Help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.High

#212 Update BetterModelClass UML to Reflect AB3
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task, priority.Low

#220 Fix bugs in EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
Labels: type.Bug, priority.High, severity.High

#222 ResetRecordsCommand - Add error messages and rewrite test cases
  src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetRecordsCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#225 Edit 'Sort' Command Syntax to Match Other Commands Better
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#224 Update unit tests for Add command related parsers
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: severity.High

#227 Updated the User Guide to include references to the 'sort' command
  docs/UserGuide.md
Labels: type.Task, priority.High

#229 Update the JAR file name to match our product
  build.gradle
Labels: type.Task, priority.Low, severity.Low

#178 Add notes GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium, severity.Medium

#233 Update GUI Minimum Dimensions
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#236 Remove redundant comments
  src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java
Labels: type.Task, priority.Low, severity.Low

#240 Change app title to BetterCallTA
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, severity.VeryLow

#243 Change notes gui
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task, priority.Medium, severity.VeryLow

#241 Fix alpha bugs found in Add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#244 Update ClearCommand to show the error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#246 Update the 'Find' command messaging
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Enhancement, priority.Medium

#247 Modify unit test for AddCommandIntegrationTest#execute_duplicatePerso…
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
Labels: type.Bug

#249 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#252 Fix grade check bounds
  src/main/java/seedu/address/model/person/Grade.java
Labels: alpha-bug

#253 Update find comment
  src/main/java/seedu/address/logic/Messages.java
Labels: alpha-bug

#255 Update the User Guide before PE-D
  docs/UserGuide.md
  docs/images/findCommandExample.png
Labels: type.Bug, priority.Medium, severity.Medium

#256 Add extra warning for the clear command
  docs/UserGuide.md
Labels: type.Task, priority.Low, severity.Low

#257 Try to update broken links
  docs/UserGuide.md
Labels: type.Task

#258 Remove page breaks
  docs/UserGuide.md
Labels: type.Task

#260 Update User Guide
  docs/UserGuide.md
  docs/images/addCommandExample.png
  docs/images/clearCommandExample.png
  docs/images/editCommandExample.png
  docs/images/fileListCommandExample.png
  docs/images/fileLoadCommandExample.png
  docs/images/fileSaveCommandExample.png
  docs/images/graphExample.png
  docs/images/listCommandExample.png
  docs/images/resetRecordsCommandExample.png
Labels: type.Task, priority.Medium, severity.Medium

#259 Update File Input Sanitization
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FileCommandParser.java
Labels: type.Bug, severity.High, alpha-bug

#335 Update Person details column of PersonCard
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.Medium, severity.Low, task.Functional

#336 Fix case sensitivity in SortCommand
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Bug, priority.High, severity.Medium, task.Functional

#339 Fix file path bugs in FileCommand
  README.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FileCommand.java
  src/main/java/seedu/address/logic/parser/FileCommandParser.java
  src/test/java/seedu/address/logic/parser/FileCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium, task.Functional

#338 Update Edit Command and remove some emojis in the UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, task.UG

#341 Edit developer guide
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, task.DG

#340 Update User Guide
  docs/UserGuide.md
Labels: priority.Medium, alpha-bug

#343 Update based on feedback
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/multipleNotesOutput.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Enhancement, priority.High, severity.Medium

#347 Fixes Bug with Argument Tokenizer
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FileCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#348 Update Developers Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Bug, priority.Medium, severity.VeryLow, task.DG

#349 Fix DeleteSequence and Model class UML diagrams
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Bug, priority.Medium, alpha-bug

#350 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Enhancement, priority.Medium, severity.VeryLow, task.DG

#351 Add puml diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/FileLoadSequenceDiagram.puml
  docs/diagrams/FileSaveSequenceDiagram.puml
Labels: priority.High

#353 Update width of diagrams in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.VeryLow, task.DG

#355 UML/DG minor changes
  docs/DeveloperGuide.md
  docs/diagrams/HistogramSequenceDiagram.puml
Labels: type.Task, priority.High, severity.VeryLow

#356 Update sequence diagram
  docs/diagrams/FileLoadSequenceDiagram.puml
  docs/diagrams/FileSaveSequenceDiagram.puml
Labels: priority.High

#359 Add sample data when running the app for the first time
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Medium, severity.Medium
